steps:
  # 1) Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/github.com/vincentporquet777/ai-backend:$COMMIT_SHA",
        "-f",
        "Dockerfile",
        "."
      ]

  # 2) Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/github.com/vincentporquet777/ai-backend:$COMMIT_SHA"
      ]

  # 3) Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "ai-backend",
        "--image",
        "gcr.io/$PROJECT_ID/github.com/vincentporquet777/ai-backend:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - "gcr.io/$PROJECT_ID/github.com/vincentporquet777/ai-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
